### PR TITLE
adr - changed the sidebar to look nicer for the rolemanagement

### PR DESCRIPTION
**Pull request by adrideba**

### CODE REVIEW

**Comment by tomkerkhove** [comment]
What's ADR 🤔

**Comment by adrideba** [comment]
> What's ADR 🤔

the initials of my name just to see which were my tasks in a glance? why it's a problem?

**Comment by tomkerkhove** [comment]
I'm not saying it's a problem; I was just wondering what it meant since it's in the PR title 🙂

**Comment by grik001** [comment]
always causing problems Adrian!

**Comment by adrideba** [comment]
Hadrian was an emperor of the Roman Empire from the years 117-138. He was a powerful ruler committed to strengthening the Empire. Hadrian oversaw several important building projects, including the Temple of Venus and Roma and Hadrian's Wall.

**Pull request merged**
